# Generated by Django 6.1 on 2026-10-03 20:16

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profiles/%Y/%m/', validators=[accounts.validators.validate_profile_image]),
        ),
    ]
