# Generated by Django 6.1 on 2026-10-03 22:43

import accounts.models
import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to=accounts.models.profile_photo_upload_path, validators=[accounts.validators.validate_profile_image]),
        ),
    ]
